const TOPIC_DISPLAY_NAMES: Record<string, string> = {
  // Domain 1
  'Brain Regions/Functions – Cerebral Cortex': 'Cerebral Cortex & Higher Functions',
  'Brain Regions/Functions – Hindbrain, Midbrain, and Subcortical Forebrain…': 'Hindbrain, Midbrain & Subcortical Structures',
  'Emotions and Stress': 'Emotion & Stress Systems',
  'Memory and Sleep': 'Memory & Sleep',
  'Nervous System, Neurons, and Neurotransmitters': 'Neurons & Neurotransmitters',
  'Neurological and Endocrine Disorders': 'Neurological & Endocrine Disorders',
  'Psychopharmacology – Antipsychotics and Antidepressants': 'Psychopharmacology: Antipsychotics & Antidepressants',
  'Psychopharmacology – Other Psychoactive Drugs': 'Psychopharmacology: Other Psychoactive Drugs',
  'Sensation and Perception': 'Sensation & Perception',
  // Domain 2
  'Classical Conditioning': 'Classical Conditioning Basics',
  'Interventions Based on Classical Conditioning': 'Classical Conditioning Interventions',
  'Interventions Based on Operant Conditioning': 'Operant Conditioning Interventions',
  'Memory and Forgetting': 'Memory & Forgetting',
  'Operant Conditioning': 'Operant Conditioning Basics',
  // Domain 3 - Social
  'Affiliation, Attraction, and Intimacy': 'Affiliation, Attraction & Intimacy',
  'Attitudes and Attitude Change': 'Attitudes & Attitude Change',
  'Persuasion': 'Persuasion & Influence',
  'Prosocial Behavior and Prejudice/Discrimination': 'Prosocial Behavior & Prejudice',
  'Social Cognition – Causal Attributions': 'Social Cognition: Attributions',
  'Social Cognition – Errors, Biases, and Heuristics': 'Social Cognition: Biases & Heuristics',
  'Social Influence – Group Influences': 'Social Influence: Groups',
  'Social Influence – Types of Influence': 'Social Influence: Compliance, Conformity & Obedience',
  // Domain 3 - Cultural
  'Cross-Cultural Issues – Identity Development Models': 'Cultural Identity Development Models',
  'Cross-Cultural Issues – Terms and Concepts': 'Core Cross-Cultural Concepts',
  // Domain 4
  'Cognitive Development': 'Cognitive Development Across Childhood',
  'Early Influences on Development – Nature vs. Nurture': 'Early Influences: Nature vs. Nurture',
  'Early Influences on Development – Prenatal Development': 'Early Influences: Prenatal Development',
  'Language Development': 'Language Development',
  'Physical Development': 'Physical Development Across Childhood',
  'School and Family Influences': 'Family & School Influences',
  'Socioemotional Development – Attachment, Emotions, and Social Relationships': 'Socioemotional Dev: Attachment & Relationships',
  'Socioemotional Development – Moral Development': 'Socioemotional Dev: Moral Growth',
  'Socioemotional Development – Temperament and Personality': 'Socioemotional Dev: Temperament & Personality',
  // Domain 5 - Assessment
  'Clinical Tests': 'Clinical Assessment Tests',
  'Interest Inventories': 'Interest Inventories',
  'MMPI-2': 'MMPI-2 & Personality Assessment',
  'Other Measures of Cognitive Ability': 'Other Cognitive Ability Tests',
  'Other Measures of Personality': 'Other Personality Measures',
  'Stanford-Binet and Wechsler Tests': 'Stanford-Binet & Wechsler Scales',
  // Domain 5 - Diagnosis
  'Anxiety Disorders and Obsessive-Compulsive Disorder': 'Anxiety & Obsessive-Compulsive Disorders',
  'Bipolar and Depressive Disorders': 'Bipolar & Depressive Disorders',
  'Disruptive, Impulse-Control, and Conduct Disorders': 'Disruptive, Impulse-Control & Conduct Disorders',
  'Feeding/Eating, Elimination, and Sleep-Wake Disor': 'Feeding/Eating, Elimination & Sleep-Wake Disorders',
  'Neurocognitive Disorders': 'Neurocognitive Disorders',
  'Neurodevelopmental Disorders': 'Neurodevelopmental Disorders',
  'Personality Disorders': 'Personality Disorders',
  'Schizophrenia Spectrum/Other Psychotic Disorders': 'Schizophrenia Spectrum & Other Psychotic Disorders',
  'Sexual Dysfunctions, Gender Dysphoria, and Paraphilic Disorders': 'Sexual Dysfunctions, Gender Dysphoria & Paraphilic Disorders',
  'Substance-Related and Addictive Disorders': 'Substance-Related & Addictive Disorders',
  'Trauma/Stressor-Related, Dissociative, and Somatic Symptom Disorders': 'Trauma, Dissociative & Somatic Symptom Disorders',
  // Domain 5 - Test Construction
  'Item Analysis and Test Reliability': 'Item Analysis & Reliability',
  'Test Score Interpretation': 'Test Score Interpretation',
  'Test Validity – Content and Construct Validity': 'Validity: Content & Construct',
  'Test Validity – Criterion-Related Validity': 'Validity: Criterion-Related',
  // Domain 6
  'Brief Therapies': 'Brief Therapies',
  'Cognitive-Behavioral Therapies': 'Cognitive-Behavioral Therapies',
  'Family Therapies and Group Therapies': 'Family & Group Therapies',
  'Prevention, Consultation, and Psychotherapy Research': 'Prevention, Consultation & Therapy Research',
  'Psychodynamic and Humanistic Therapies': 'Psychodynamic & Humanistic Therapies',
  // Domain 7
  'Correlation and Regression': 'Correlation & Regression',
  'Inferential Statistical Tests': 'Inferential Statistical Tests',
  'Overview of Inferential Statistics': 'Inferential Statistics Overview',
  'Research – Internal/External Validity': 'Research Validity: Internal & External',
  'Research – Single-Subject and Group Designs': 'Single-Subject & Group Designs',
  'Types of Variables and Data': 'Variables & Data Types',
  // Domain 8
  'APA Ethics Code Over and Standards 1 & 2': 'Ethics: Overview & Standards 1-2',
  'APA Ethics Code Standards 3 & 4': 'Ethics: Standards 3-4',
  'APA Ethics Code Standards 5 & 6': 'Ethics: Standards 5-6',
  'APA Ethics Code Standards 7 & 8': 'Ethics: Standards 7-8',
  'APA Ethics Code Standards 9 & 10': 'Ethics: Standards 9-10',
  'Professional Issues': 'Professional Practice Issues',
  // Domain 3-5-6 Organizational Psychology
  'Career Choice and Development': 'Career Choice & Development',
  'Employee Selection – Evaluation of Techniques': 'Employee Selection: Evaluating Techniques',
  'Employee Selection – Techniques': 'Employee Selection Techniques',
  'Job Analysis and Performance Assessment': 'Job Analysis & Performance Appraisal',
  'Organizational Change and Development': 'Organizational Change & Development',
  'Organizational Decision-Making': 'Organizational Decision-Making',
  'Organizational Leadership': 'Organizational Leadership',
  'Organizational Theories': 'Organizational Theories',
  'Satisfaction, Commitment, and Stress': 'Job Satisfaction, Commitment & Stress',
  'Theories of Motivation': 'Work Motivation Theories',
  'Training Methods and Evaluation': 'Training Methods & Evaluation',
}

export function getLessonDisplayName(topicName: string): string {
  return TOPIC_DISPLAY_NAMES[topicName] ?? topicName
}
