import {
  AbsoluteFill,
  Easing,
  Img,
  interpolate,
  staticFile,
  useCurrentFrame,
  useVideoConfig,
} from "remotion";
import {
  FONT_GEIST,
  PANEL_RADIUS,
  PANEL_SHADOW,
  SITE_BG,
  TEXT_MUTED,
} from "./design";

// One illustration moment: a PNG from public/ (AI-generated by the pipeline,
// or future hand-drawn art) in a centered rounded panel with an optional
// caption line. Slow fade plus a 2% scale settle — the calmest move in the
// set, since the art itself is the event.
export const IllustrationCue: React.FC<{
  image: string;
  caption?: string;
}> = ({ image, caption }) => {
  const frame = useCurrentFrame();
  const { fps } = useVideoConfig();

  const progress = interpolate(frame, [0, 0.7 * fps], [0, 1], {
    extrapolateLeft: "clamp",
    extrapolateRight: "clamp",
    easing: Easing.bezier(0.16, 1, 0.3, 1),
  });

  return (
    <AbsoluteFill style={{ justifyContent: "center", alignItems: "center" }}>
      <div
        style={{
          backgroundColor: SITE_BG,
          borderRadius: PANEL_RADIUS,
          width: "78%",
          padding: 28,
          fontFamily: FONT_GEIST,
          boxShadow: PANEL_SHADOW,
          opacity: progress,
          transform: `scale(${0.98 + 0.02 * progress})`,
        }}
      >
        <Img
          src={staticFile(image)}
          style={{ width: "100%", display: "block", borderRadius: 18 }}
        />
        {caption ? (
          <div
            style={{
              fontSize: 30,
              fontWeight: 400,
              color: TEXT_MUTED,
              textAlign: "center",
              marginTop: 22,
              marginBottom: 6,
              lineHeight: 1.35,
            }}
          >
            {caption}
          </div>
        ) : null}
      </div>
    </AbsoluteFill>
  );
};
