export interface SenseSubscale {
  id: string
  name: string
  citation: string
  items: string[]
}

export interface SenseDomain {
  number: number
  name: string
  subscales: SenseSubscale[]
}

export const RESPONSE_SCALE = [
  { value: 1, label: 'Never' },
  { value: 2, label: 'Rarely' },
  { value: 3, label: 'Sometimes' },
  { value: 4, label: 'Often' },
  { value: 5, label: 'Always' },
] as const

export const SENSE_DOMAINS: SenseDomain[] = [
  {
    number: 1,
    name: 'Somatic Awareness',
    subscales: [
      {
        id: 'interoception',
        name: 'Interoception',
        citation: 'Adapted from MAIA-2 "Noticing" and "Body Listening" subscales (Mehling et al., 2018; Rogowska et al., 2023).',
        items: [
          'I notice subtle changes in my breathing before they become uncomfortable.',
          'I can detect early signs of hunger or thirst before they become intense.',
          'I am aware of my heart rate changing during different activities.',
          'I notice tension building in my muscles before it becomes painful.',
          'I can sense when my energy level is starting to decline.',
          'I recognize when my body needs rest before I feel exhausted.',
          'I notice changes in my body temperature (feeling warm or cool).',
          'I can detect digestive sensations (stomach gurgling, fullness) as they occur.',
          'I am aware of my body\u2019s signals when I need to use the bathroom.',
          'I notice when my breathing becomes shallow or restricted.',
        ],
      },
      {
        id: 'somatic-regulation',
        name: 'Somatic Regulation',
        citation: 'Adapted from MAIA-2 "Self-Regulation" subscale and somatic regulation literature (Mehling et al., 2018; Rogowska et al., 2023).',
        items: [
          'When I notice tension in my body, I can intentionally relax those muscles.',
          'I can slow my breathing when I notice it becoming rapid.',
          'When my shoulders tighten during stress, I can consciously release them.',
          'I can shift my posture to reduce physical discomfort when I notice it.',
          'When my jaw clenches, I can deliberately relax it.',
          'I can use breathing techniques to calm my body when activated.',
          'When I feel my heart racing, I can take steps to slow it down.',
          'I can reduce muscle tension through intentional movement or stretching.',
          'When my hands clench into fists, I can consciously open them.',
          'I can adjust my physical state through grounding techniques (e.g., feet on floor, hands on surface).',
        ],
      },
      {
        id: 'proprioception',
        name: 'Proprioception',
        citation: 'Adapted from the Postural Awareness Scale and proprioception assessment literature (Da Costa Silva et al., 2022; Hillier et al., 2015).',
        items: [
          'I am aware of where my limbs are positioned without looking at them.',
          'I notice when my shoulders creep up toward my ears.',
          'I can describe where tension is located in my body (e.g., "upper back," "left shoulder").',
          'I am aware of my posture throughout the day.',
          'I notice when my jaw is clenched or tight.',
          'I can sense the difference between relaxed and tense muscles.',
          'I am aware of how much pressure I\u2019m applying when gripping objects.',
          'I notice when I\u2019m slouching or hunching forward.',
          'I can feel the position of my feet and legs while sitting or standing.',
          'I am aware of my body\u2019s boundaries and position in space.',
        ],
      },
      {
        id: 'recovery-curve',
        name: 'Recovery Curve',
        citation: 'Adapted from the Recovery Experience Questionnaire and stress recovery literature (Kazlauskas et al., 2023; Sonnentag & Fritz, 2007).',
        items: [
          'After a stressful event, my body returns to a calm state within a few hours.',
          'Physical tension from a difficult conversation resolves by the end of the day.',
          'When something startles me, my heart rate returns to normal within minutes.',
          'After an argument, muscle tightness in my body releases within a reasonable timeframe.',
          'I don\u2019t carry physical tension from one day into the next.',
          'After a stressful meeting, my breathing returns to normal relatively quickly.',
          'Physical activation from stress doesn\u2019t linger for days afterward.',
          'My body naturally "winds down" after stressful situations end.',
          'I don\u2019t remain physically braced or tense long after a stressor has passed.',
          'My sleep is not disrupted for multiple nights after a single stressful event.',
        ],
      },
    ],
  },
  {
    number: 2,
    name: 'Emotional Integration',
    subscales: [
      {
        id: 'emotional-regulation',
        name: 'Emotional Regulation',
        citation: 'Adapted from the Emotion Regulation Skills Questionnaire and ERQ-30 (Grant et al., 2018; Preece & Gross, 2025).',
        items: [
          'I can experience strong emotions without losing control of my behavior.',
          'When I feel intense emotions, I can still think clearly.',
          'I can stay engaged in difficult conversations without shutting down.',
          'When upset, I can choose how to respond rather than reacting impulsively.',
          'I can tolerate uncomfortable emotions without needing to immediately escape them.',
          'Strong feelings don\u2019t cause me to become completely disorganized.',
          'I can experience anger without lashing out at others.',
          'When emotionally activated, I can still make reasonable decisions.',
          'I don\u2019t need to avoid situations just because they might bring up difficult emotions.',
          'I can sit with emotional discomfort without it overwhelming me.',
        ],
      },
      {
        id: 'emotional-differentiation',
        name: 'Emotional Differentiation',
        citation: 'Adapted from the Perth Alexithymia Questionnaire and Toronto Alexithymia Scale literature (Preece et al., 2023, 2024).',
        items: [
          'I can identify the specific emotion I\u2019m feeling (e.g., frustrated vs. disappointed).',
          'I can distinguish between feeling anxious and feeling sad.',
          'I notice when I\u2019m experiencing more than one emotion at the same time.',
          'I can put words to my emotional experiences with precision.',
          'I recognize the difference between anger and hurt.',
          'I can identify mixed emotions (e.g., "I feel both relieved and guilty").',
          'I don\u2019t describe my feelings in vague terms like "fine" or "bad."',
          'I can tell the difference between physical sensations and emotions.',
          'I recognize subtle differences in emotional states (e.g., irritated vs. enraged).',
          'I can name my emotions even when they\u2019re complex or layered.',
        ],
      },
      {
        id: 'relational-safety-template',
        name: 'Relational Safety Template',
        citation: 'Adapted from attachment security literature and Experiences in Close Relationships-Revised measures (Brenk-Franz et al., 2018; Justo-N\u00fa\u00f1ez et al., 2022).',
        items: [
          'I feel comfortable expressing my needs in close relationships.',
          'I trust that my partner/close others can handle my emotional expression.',
          'I believe conflict can strengthen rather than damage my relationships.',
          'I expect that expressing vulnerability will be met with understanding.',
          'I feel safe sharing difficult emotions with people I\u2019m close to.',
          'I trust that disagreements won\u2019t lead to abandonment or rejection.',
          'I believe my relationships can withstand emotional honesty.',
          'I feel secure enough to bring up concerns with important people in my life.',
          'I expect that expressing upset feelings will be tolerated, not punished.',
          'I trust that emotional expression will bring me closer to others, not push them away.',
        ],
      },
    ],
  },
  {
    number: 3,
    name: 'Neurocognitive Load',
    subscales: [
      {
        id: 'cognitive-load-tolerance',
        name: 'Cognitive Load Tolerance',
        citation: 'Adapted from the Working Memory Questionnaire and cognitive load literature (Le\u00f3n-Dom\u00ednguez et al., 2015; Vallat-Azouvi et al., 2012).',
        items: [
          'I can think clearly even when I\u2019m emotionally upset.',
          'During stressful situations, I can still organize my thoughts coherently.',
          'My mind doesn\u2019t go blank when I\u2019m under pressure.',
          'I can articulate my point during conflict even when activated.',
          'When anxious, I can still access the information I need.',
          'Emotional activation doesn\u2019t cause my thinking to become scattered.',
          'I can problem-solve effectively even when stressed.',
          'During high-pressure moments, I can still think through my options.',
          'Strong emotions don\u2019t completely disrupt my ability to think.',
          'I can maintain focus on tasks even when emotionally uncomfortable.',
        ],
      },
      {
        id: 'cognitive-flexibility',
        name: 'Cognitive Flexibility',
        citation: 'Adapted from the Cognitive Flexibility Inventory, Cognitive Flexibility Scale, and review literature (Hohl & Dolcos, 2023; Johnco et al., 2014).',
        items: [
          'I can shift my attention from one task to another without difficulty.',
          'I adapt easily when plans change unexpectedly.',
          'I can consider multiple perspectives on a situation.',
          'I transition smoothly between work mode and relaxation.',
          'I can revise my opinion when presented with new information.',
          'I don\u2019t get stuck on one interpretation of events.',
          'I can adjust my approach when my initial strategy isn\u2019t working.',
          'I can let go of one task and move on to another without ruminating.',
          'I can see situations from different angles rather than in black-and-white terms.',
          'I adapt my behavior to fit different social contexts.',
        ],
      },
      {
        id: 'working-memory-capacity',
        name: 'Working Memory Capacity',
        citation: 'Adapted from the Working Memory Questionnaire and NIH Toolbox List Sorting Test literature (Tulsky et al., 2014; Vallat-Azouvi et al., 2012).',
        items: [
          'I can follow complex conversations without losing track of the discussion.',
          'I can hold multiple pieces of information in mind while making decisions.',
          'I manage multi-step tasks without becoming overwhelmed.',
          'I can remember instructions while carrying them out.',
          'I can keep track of several things at once without confusion.',
          'I don\u2019t lose my train of thought when interrupted.',
          'I can mentally organize information while listening to someone speak.',
          'I can plan ahead while managing current demands.',
          'I can integrate new information with what I already know in real time.',
          'I don\u2019t become confused when several demands occur simultaneously.',
        ],
      },
    ],
  },
  {
    number: 4,
    name: 'Sensory Processing',
    subscales: [
      {
        id: 'sensory-threshold',
        name: 'Sensory Threshold',
        citation: 'Adapted from the Adult Sensory Processing Scale and Sensory Sensitivity Scales (Aykan et al., 2020; Blanche et al., 2014).',
        items: [
          'Bright lights (e.g., fluorescent, overhead) are tolerable for extended periods.',
          'Background noise in busy environments doesn\u2019t significantly disrupt my functioning.',
          'I can work or concentrate in moderately stimulating spaces (e.g., caf\u00e9s, open offices).',
          'Normal levels of sound don\u2019t cause me irritability or distress.',
          'Typical indoor lighting doesn\u2019t feel overwhelming or draining.',
          'I can tolerate being in crowded spaces without becoming overstimulated.',
          'Everyday sensory input (sounds, lights, textures) doesn\u2019t quickly exhaust me.',
          'I don\u2019t need to leave environments due to sensory overload.',
          'Moderate environmental stimulation is manageable without strain.',
          'I can function in typical sensory environments without significant discomfort.',
        ],
      },
      {
        id: 'sensory-modulation-capacity',
        name: 'Sensory Modulation Capacity',
        citation: 'Adapted from the SENSE Questionnaire and sensory modulation literature (Engel-Yeger, 2024; Podoly & Ben-Sasson, 2020).',
        items: [
          'When overstimulated, I know what sensory adjustments will help (e.g., dimming lights, reducing noise).',
          'I can increase sensory input (e.g., music, movement) when I need to focus or energize.',
          'I adjust my environment\u2019s lighting based on my needs.',
          'I use background noise or silence strategically depending on what helps me concentrate.',
          'I can modify my sensory environment to support my regulation.',
          'When feeling overwhelmed, I know how to reduce sensory input.',
          'I use movement or physical pressure to help myself refocus when needed.',
          'I recognize when I need more or less sensory stimulation.',
          'I actively manage my sensory environment rather than enduring discomfort.',
          'I can identify which sensory changes would improve my current state.',
        ],
      },
      {
        id: 'sensory-discrimination',
        name: 'Sensory Discrimination',
        citation: 'Adapted from sensory discrimination and habituation literature (Bar-Shalita et al., 2008; Podoly & Ben-Sasson, 2020).',
        items: [
          'I can accurately identify where on my body I\u2019ve been touched.',
          'I can distinguish between different types of physical sensations (pressure vs. pain).',
          'I can locate exactly where discomfort or tension is in my body.',
          'I can tell the difference between subtle variations in temperature.',
          'I can identify the specific quality of bodily sensations (sharp, dull, tingling).',
          'I don\u2019t describe sensations as vague or "weird" without being able to specify further.',
          'I can pinpoint the exact location of physical discomfort.',
          'I can differentiate between similar but distinct sensations.',
          'I can describe sensations with precision rather than general terms.',
          'I can clearly sense the boundaries and location of physical sensations.',
        ],
      },
    ],
  },
  {
    number: 5,
    name: 'Environmental Regulation',
    subscales: [
      {
        id: 'contextual-mapping',
        name: 'Contextual Mapping',
        citation: 'Adapted from environmental awareness and social cognition frameworks (Heinemann et al., 2016; Lichtveld et al., 2019).',
        items: [
          'I quickly understand the behavioral expectations of new environments.',
          'I can read the formality level of a setting and adjust my behavior accordingly.',
          'I recognize when a situation requires high vs. low social energy.',
          'I understand the implicit "rules" of different social contexts.',
          'I can identify the functional flow of spaces (e.g., where to stand, how people move).',
          'I don\u2019t feel confused about how to behave in unfamiliar settings.',
          'I can sense the social atmosphere of a room when I enter it.',
          'I recognize contextual cues that signal what\u2019s expected of me.',
          'I can distinguish between casual and formal environments and respond appropriately.',
          'I understand the structure and expectations of different settings without explicit instruction.',
        ],
      },
      {
        id: 'environmental-modulation',
        name: 'Environmental Modulation',
        citation: 'Adapted from environmental factors assessment literature and self-regulation frameworks (Heinemann et al., 2016).',
        items: [
          'When I need to concentrate, I move to a quieter workspace.',
          'I adjust my environment (lighting, noise, temperature) to support my functioning.',
          'When overstimulated, I take steps to modify my surroundings.',
          'I change my physical environment when it\u2019s interfering with my goals.',
          'I can identify environmental factors that are contributing to my dysregulation.',
          'I don\u2019t remain in unsupportive environments when I have the option to change them.',
          'I actively create environmental conditions that help me function well.',
          'When my environment isn\u2019t working for me, I make adjustments.',
          'I modify my workspace or living space to match my regulatory needs.',
          'I recognize when environmental changes would improve my state and make them.',
        ],
      },
      {
        id: 'agency',
        name: 'Agency',
        citation: 'Adapted from agency, empowerment, self-efficacy, and locus of control literature.',
        items: [
          'I believe I can influence my circumstances through my actions.',
          'When faced with an unsustainable situation, I take steps to change it.',
          'I don\u2019t feel helpless in the face of environmental stressors.',
          'I believe my efforts can meaningfully improve my situation.',
          'I see myself as capable of adapting to or modifying challenging circumstances.',
          'I don\u2019t endure difficult conditions without attempting to make changes.',
          'I feel empowered to alter aspects of my environment that aren\u2019t working.',
          'I believe I have some control over my life circumstances.',
          'When something isn\u2019t working, I think, "What can I do about this?" rather than, "There\u2019s nothing I can do."',
          'I take initiative to create change rather than waiting for circumstances to change on their own.',
        ],
      },
    ],
  },
  {
    number: 6,
    name: 'Coherence',
    subscales: [
      {
        id: 'coherence',
        name: 'Coherence',
        citation: 'Generated construct adapted from interoceptive awareness, alexithymia, and emotional awareness literature (Mehling et al., 2018; Preece et al., 2023; Rogowska et al., 2023).',
        items: [
          'My physical sensations match what I\u2019m feeling emotionally.',
          'What my body is telling me aligns with what I\u2019m thinking.',
          'When I say "I\u2019m fine," my body actually feels fine.',
          'My emotional experience and physical state communicate the same message.',
          'I don\u2019t experience a disconnect between my body, emotions, and thoughts.',
          'If my body is tense, I can identify the corresponding emotion.',
          'My cognitive interpretation of situations matches my bodily response.',
          'I don\u2019t feel physically activated while insisting I\u2019m emotionally neutral.',
          'My internal experience (body + emotion + thought) tells a coherent story.',
          'When asked how I\u2019m doing, my body, feelings, and thoughts give the same answer.',
        ],
      },
    ],
  },
]
