import type { Metadata } from 'next'
import LabClient from './lab-client'

export const metadata: Metadata = {
  title: 'Lab | thePsychology.ai',
  description: 'Clinical tools, practice automations, and experimental projects from thePsychology.ai.',
}

const projects = [
  {
    id: 1,
    title: 'NYSED Psych License Check',
    description: 'After you got your hours and passed the EPPP, you\u2019re waiting for the board. We check daily and email you when your license is recognized. Free. No more refreshing.',
    category: 'getting-licensed',
    categoryLabel: '01 Getting Licensed',
    href: '/lab/license-watch',
    status: 'live' as const,
    tags: ['Email Alerts', 'NYSED', 'Free'],
  },
  {
    id: 2,
    title: 'Inzinna SP Notes',
    description: 'Local-first clinical documentation copilot for intake capture, diagnostic review, SOAP drafts, and treatment-plan support before anything touches the chart.',
    category: 'clinical-practice',
    categoryLabel: '02 Psychologist Tools',
    href: '/lab/inzinna-sp-notes',
    status: 'beta' as const,
    tags: ['Chrome Extension', 'Local AI', 'SOAP Draft', 'Diagnostics'],
    group: 'inzinna' as const,
  },
  {
    id: 3,
    title: 'ZocDoc to SimplePractice',
    description: 'Capture a ZocDoc referral once, then fill SimplePractice demographics, insurance, appointments, and VOB draft without double entry.',
    category: 'clinical-practice',
    categoryLabel: '02 Psychologist Tools',
    href: '/lab/zocdoc-simplepractice',
    status: 'dev' as const,
    tags: ['Chrome Extension', 'Intake Automation', 'Insurance', 'VOB'],
    group: 'inzinna' as const,
  },
  {
    id: 4,
    title: 'SENSE',
    description: 'A mind-body assessment tool developed by Dr. Neha Menon.',
    category: 'clinical-practice',
    categoryLabel: '02 Psychologist Tools',
    href: '/lab/sense',
    status: 'dev' as const,
    tags: ['Next.js App', 'Prisma', 'Clinical'],
  },
  {
    id: 5,
    title: 'ADHD-RS',
    description: 'No more hand-summing 18 items and flipping through norm tables. Enter responses, get subscale scores, symptom counts, and a report-ready summary instantly.',
    category: 'clinical-practice',
    categoryLabel: '02 Psychologist Tools',
    href: '/lab/adhd-rs',
    status: 'dev' as const,
    tags: ['Assessment', 'Auto-Scoring', 'ADHD'],
    group: 'inzinna' as const,
  },
  {
    id: 6,
    title: 'BAARS-IV',
    description: 'The only digital BAARS-IV scorer. Auto-calculates subscales, SCT, symptom counts, and age-banded percentiles. Drops a clinical summary straight into your notes.',
    category: 'clinical-practice',
    categoryLabel: '02 Psychologist Tools',
    href: '/lab/baars',
    status: 'dev' as const,
    tags: ['Assessment', 'Auto-Scoring', 'ADHD'],
    group: 'inzinna' as const,
  },
  {
    id: 11,
    title: 'Payroll Autofill',
    description: 'Upload a SimplePractice CSV, get per-clinician pay totals with adjusted hourly rates that make JustWorks math land exactly. Chrome extension fills the time cards.',
    category: 'clinical-practice',
    categoryLabel: '02 Psychologist Tools',
    href: '/lab/inzinna/payroll',
    status: 'dev' as const,
    tags: ['Chrome Extension', 'JustWorks', 'SimplePractice', 'Payroll'],
    group: 'inzinna' as const,
  },
  {
    id: 9,
    title: 'Clinician Survey',
    description: 'Native slide deck presenting findings from the Inzinna clinician needs-assessment survey: priorities, AI use-case demand, barriers, and privacy dealbreakers.',
    category: 'clinical-practice',
    categoryLabel: '02 Psychologist Tools',
    href: '/lab/inzinna/clinician-survey',
    status: 'live' as const,
    tags: ['Survey', 'Slide Deck', 'Needs Assessment'],
    group: 'inzinna' as const,
  },
  {
    id: 7,
    title: 'Chinese Calligraphy Studio',
    description: 'Type English. Get Chinese. See it in real calligraphy fonts.',
    category: 'creative',
    categoryLabel: '03 Creative',
    href: '/lab/calligraphy',
    status: 'live' as const,
    tags: ['Interactive', 'Translation'],
  },
  {
    id: 10,
    title: 'Sound Remake',
    description: 'Feed it any sound you want to recreate. It figures out the recipe, opens your synth, and turns the knobs for you.',
    category: 'creative',
    categoryLabel: '03 Creative',
    href: '/lab/sound-remake',
    status: 'soon' as const,
    tags: ['Audio Analysis', 'VST3/JUCE', 'Preset Generation', 'Sound Design'],
  },
  {
    id: 8,
    title: 'Dental Figure Extractor',
    description: 'Upload a textbook PDF. Get a PowerPoint with every figure on its own slide, captions included. Drag them into your study decks.',
    category: 'dental',
    categoryLabel: '04 Dental',
    href: '/lab/dental',
    status: 'beta' as const,
    tags: ['PyMuPDF', 'PowerPoint', 'Dental Students'],
  },
]

export default function LabPage() {
  return <LabClient projects={projects} />
}
