export interface NoteTemplate {
  id: string
  name: string
  type: 'therapy' | 'assessment'
  template: string
}

export const NOTE_TEMPLATES: NoteTemplate[] = [
  {
    id: 'therapy_session',
    name: 'Therapy Session Note',
    type: 'therapy',
    template: `**SENSE Lens Session Note**

**Client:** {{clientName}}
**Date:** {{date}}
**Session Type:** Individual Therapy
**Setting:** {{context}}

---

**BASELINE PROFILE (SENSE Domains)**

| Domain | Rating | Clinical Significance |
|--------|--------|----------------------|
| Somatic | {{somaticRating}}/5 | {{somaticSignificance}} |
| Emotional | {{emotionalRating}}/5 | {{emotionalSignificance}} |
| Neurological | {{neurologicalRating}}/5 | {{neurologicalSignificance}} |
| Social | {{socialRating}}/5 | {{socialSignificance}} |
| Environmental | {{environmentalRating}}/5 | {{environmentalSignificance}} |

**State Tag:** {{stateTag}}
**Primary Body System:** {{bodySystem}}
{{#sensoryModifiers}}
**Sensory Modifiers:** {{sensoryModifiers}}
{{/sensoryModifiers}}

---

**CLINICAL HYPOTHESES**

Sensory processing may be a contributing factor in the following ways:

1. {{hypothesis1}}

2. {{hypothesis2}}

---

**TREATMENT PLAN**

**Targets:** {{targets}}

**Intervention:** {{interventionName}}
{{#interventionDescription}}
{{interventionDescription}}
{{/interventionDescription}}

**Measure:** {{measure}}

**Practice Frequency:** {{practiceFrequency}}

---

**GUARDRAIL STATEMENT**

*The SENSE framework provides a structured lens for considering how sensory processing may contribute to a client's presentation. It is intended to complement—not replace—comprehensive clinical assessment. Sensory considerations are one factor among many in understanding each client's unique needs.*

---

Generated by SENSE Lens | thepsychology.ai/SENSE`,
  },
  {
    id: 'assessment_summary',
    name: 'Assessment Summary',
    type: 'assessment',
    template: `**SENSE Lens Assessment Summary**

**Client:** {{clientName}}
**Age:** {{clientAge}}
**Date:** {{date}}
**Evaluator:** _______________

---

**PRESENTING CONCERNS**

{{presentingConcerns}}

---

**SENSE PROFILE SUMMARY**

This assessment utilized the SENSE Lens framework to evaluate the client's presentation across five interconnected domains:

**Somatic ({{somaticRating}}/5):** {{somaticNarrative}}

**Emotional ({{emotionalRating}}/5):** {{emotionalNarrative}}

**Neurological ({{neurologicalRating}}/5):** {{neurologicalNarrative}}

**Social ({{socialRating}}/5):** {{socialNarrative}}

**Environmental ({{environmentalRating}}/5):** {{environmentalNarrative}}

---

**AROUSAL STATE OBSERVATIONS**

Primary State: {{stateTag}}
Body System Involvement: {{bodySystem}}

---

**SENSORY PROCESSING CONSIDERATIONS**

{{#sensoryModifiers}}
The following sensory processing characteristics were noted:
{{sensoryModifiers}}
{{/sensoryModifiers}}

---

**CLINICAL HYPOTHESES**

Based on this assessment, sensory processing may contribute to the client's presentation in the following ways:

1. {{hypothesis1}}

2. {{hypothesis2}}

---

**RECOMMENDATIONS**

{{recommendations}}

---

**GUARDRAIL STATEMENT**

*The SENSE framework provides a structured lens for considering how sensory processing may contribute to a client's presentation. It is intended to complement—not replace—comprehensive clinical assessment and should be interpreted alongside other evaluation findings.*

---

Generated by SENSE Lens | thepsychology.ai/SENSE`,
  },
]

export function getTemplateById(id: string): NoteTemplate | undefined {
  return NOTE_TEMPLATES.find(t => t.id === id)
}
