import { DOMAINS, STATE_TAGS, BODY_SYSTEMS, RATING_LABELS, SENSORY_MODIFIERS } from './enums'
import { getInterventionById } from './interventions'

interface SessionData {
  clientName: string
  clientAge?: number | null
  date: string
  context?: string | null
  somaticRating?: number | null
  emotionalRating?: number | null
  neurologicalRating?: number | null
  socialRating?: number | null
  environmentalRating?: number | null
  stateTag?: string | null
  bodySystem?: string | null
  sensoryModifiers?: string | null
  hypothesis1?: string | null
  hypothesis2?: string | null
  targets?: string | null
  interventionId?: string | null
  interventionName?: string | null
  measure?: string | null
  practiceFrequency?: string | null
}

function getRatingSignificance(rating: number | null | undefined): string {
  if (!rating) return 'Not assessed'
  const label = RATING_LABELS.find(r => r.value === rating)
  return label?.label || 'Unknown'
}

function formatStateTag(stateTagId: string | null | undefined): string {
  if (!stateTagId) return 'Not assessed'
  const tag = STATE_TAGS.find(t => t.id === stateTagId)
  return tag?.label || stateTagId
}

function formatBodySystem(systemId: string | null | undefined): string {
  if (!systemId) return 'Not specified'
  const system = BODY_SYSTEMS.find(s => s.id === systemId)
  return system?.label || systemId
}

function formatSensoryModifiers(modifiersJson: string | null | undefined): string {
  if (!modifiersJson) return ''
  try {
    const modifierIds = JSON.parse(modifiersJson) as string[]
    if (!modifierIds.length) return ''
    return modifierIds
      .map(id => SENSORY_MODIFIERS.find(m => m.id === id)?.label || id)
      .join(', ')
  } catch {
    return modifiersJson
  }
}

function formatTargets(targetsJson: string | null | undefined): string {
  if (!targetsJson) return 'Not specified'
  try {
    const targets = JSON.parse(targetsJson) as string[]
    if (!targets.length) return 'Not specified'
    return targets.join(', ')
  } catch {
    return targetsJson
  }
}

export function renderTherapyNote(data: SessionData): string {
  const intervention = data.interventionId ? getInterventionById(data.interventionId) : null

  let note = `**SENSE Lens Session Note**

**Client:** ${data.clientName}
**Date:** ${data.date}
**Session Type:** Individual Therapy
**Setting:** ${data.context || 'Not specified'}

---

**BASELINE PROFILE (SENSE Domains)**

| Domain | Rating | Clinical Significance |
|--------|--------|----------------------|
| Somatic | ${data.somaticRating || '-'}/5 | ${getRatingSignificance(data.somaticRating)} |
| Emotional | ${data.emotionalRating || '-'}/5 | ${getRatingSignificance(data.emotionalRating)} |
| Neurological | ${data.neurologicalRating || '-'}/5 | ${getRatingSignificance(data.neurologicalRating)} |
| Social | ${data.socialRating || '-'}/5 | ${getRatingSignificance(data.socialRating)} |
| Environmental | ${data.environmentalRating || '-'}/5 | ${getRatingSignificance(data.environmentalRating)} |

**State Tag:** ${formatStateTag(data.stateTag)}
**Primary Body System:** ${formatBodySystem(data.bodySystem)}`

  const modifiers = formatSensoryModifiers(data.sensoryModifiers)
  if (modifiers) {
    note += `\n**Sensory Modifiers:** ${modifiers}`
  }

  note += `

---

**CLINICAL HYPOTHESES**

Sensory processing may be a contributing factor in the following ways:

1. ${data.hypothesis1 || 'Not specified'}

2. ${data.hypothesis2 || 'Not specified'}

---

**TREATMENT PLAN**

**Targets:** ${formatTargets(data.targets)}

**Intervention:** ${data.interventionName || intervention?.name || 'Not specified'}`

  if (intervention?.description) {
    note += `\n*${intervention.description}*`
  }

  note += `

**Measure:** ${data.measure || 'Not specified'}

**Practice Frequency:** ${data.practiceFrequency || 'Not specified'}

---

**GUARDRAIL STATEMENT**

*The SENSE framework provides a structured lens for considering how sensory processing may contribute to a client's presentation. It is intended to complement—not replace—comprehensive clinical assessment. Sensory considerations are one factor among many in understanding each client's unique needs.*

---

Generated by SENSE Lens | thepsychology.ai/SENSE`

  return note
}

export function generateNote(data: SessionData): string {
  return renderTherapyNote(data)
}
